apiVersion: v1
kind: ConfigMap
metadata:
  name: travelo-config
  namespace: travelo
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/travelo"
  SPRING_DATASOURCE_USERNAME: "travelo"
  MYSQL_DATABASE: "travelo"
  MYSQL_USER: "travelo"
