apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: travelo
type: Opaque
data:
  MYSQL_PASSWORD: dHJhdmVsbzEyMw==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: dHJhdmVsbzEyMw==
